# Generated by rust2rpm 23
%bcond_without check

Name:           rust-helix
Version:        22.08.1
Release:        1%{?dist}
Summary:        A post-modern modal text editor

License:        MPL-2.0
URL:            https://helix-editor.com
Source0:        https://github.com/helix-editor/helix/archive/%{version}.tar.gz
ExclusiveArch:  x86_64 ppc64le
BuildRequires:  rust-packaging >= 21
BuildRequires:  rust-anyhow-devel
BuildRequires:  rust-arc-swap-devel
BuildRequires:  rust-chrono-devel
BuildRequires:  rust-content_inspector-devel
BuildRequires:  rust-crossterm-devel

%description
Helix is a Rust-based post-modern text editor which is heavily
inspired by Kakoune text editor. It comes with many built-in
features such as Tree-sitter integration, fuzzy finder, beautiful
themes, auto closing backet pairs and more.

%package helix
Summary:   Helix the post-modern text editor 
%description helix
Helix text editor

%files helix
%license LICENSE
%doc README.md CHANGELOG.md
%{_bindir}/hx

%prep
%autosetup -n helix-%{version_no_tilde} -p1
%cargo_prep

%build
%cargo_build -a

%install
%cargo_install -a

%if %{with check}
%check
%cargo_test -a
%endif

%changelog
* Mon Nov 21 2022 Trung Lê <8@tle.id.au> - 22.08.1-1

- Initial package
