# Generated by rust2rpm 23
%bcond_without check
%global debug_package %{nil}
%global crate helix-editor

Name:           rust-%{crate}
Version:        22.08.1
Release:        1%{?dist}
Summary:        A post-modern modal text editor

License:        MPL-2.0
URL:            https://crates.io/crates/helix-editor
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
BuildRequires:  rust-packaging >= 21

%global _description %{expand:
A post-modern modal text editor.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}

%description    devel %{_description}

%files       -n %{crate}
%license LICENSE
%doc README.md CHANGELOG.md
%{_bindir}/hx

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires -a

%build
%cargo_build -a

%install
%cargo_install -a

%if %{with check}
%check
%cargo_test -a
%endif

%changelog
* Mon Nov 21 2022 Trung Lê <8@tle.id.au> - 22.08.1-1

- Initial package
